name: nodejs

on:
  push:
    paths:
      - '**/**'
      - '!**/*.md/**'
env:
  COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
  PULL_NUMBER: ${{ github.event.pull_request.number }}
  RUN_ID: ${{ github.run_id }}
  FORCE_COLOR: 2

jobs:
  pipeline:
    name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      PACKED_JS_PATH: 'dist/**'

    strategy:
      fail-fast: false
      matrix:
        node-version: ['16.x']
        os: ['ubuntu-latest']

    # this line will prevent forks of this repo from uploading lsif indexes
    if: github.repository == 'libsushi'
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Extract branch name
        id: extractBranch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install project dependencies
        run: yarn --prefer-offline
        id: install

      - name: Install project dependencies
        run: yarn run build
        id: build

      - name: Pack
        run: npm pack
      - name: Check packed js changes
        id: packedJsStatus
        run: echo ::set-output name=changes::$(git status ${{ env.PACKED_JS_PATH }} --porcelain)

      - name: Commit packed js
        id: commitPackedJs
        if: steps.packedJsStatus.outputs.changes
        run: |
          git config --local user.email "janitor@manifoldfinance.com"
          git config --local user.name "0xJanitor"
          git add ${{ env.PACKED_JS_PATH }}
          git commit -m "Pack with dependencies to ${{ env.PACKED_JS_PATH }}"

      - name: Push packed js
        if: steps.commitPackedJs.outcome == 'success'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
          force: true
          branch: ${{ steps.extractBranch.outputs.branch }}

      - name: Generate index
        uses: docker://sourcegraph/scip-typescript:latest
        with:
          args: scip-typescript index
      - name: Upload index
        uses: docker://sourcegraph/src-cli:latest
        with:
          # this will upload to Sourcegraph.com, you may need to substitute a different command
          # by default, we ignore failures to avoid disrupting CI pipelines with non-critical errors.
          args: lsif upload -github-token=${{ secrets.GITHUB_TOKEN }} -ignore-upload-failure
